@startuml
left to right direction
:Agente: as Actor


(Evaluar Solicitud de Crédito) as Evaluar
(Solicitar Información adicional al cliente) as Solicitar

Actor --> Evaluar
Solicitar ..>"<<extend>>" Evaluar
note right of Solicitar
Si ingresos <1000
end note

@enduml
