@startuml
left to right direction
:Cliente Bancario: as ActorAscen
:ClienteCorporativo: as ActorDescendiente
:ClienteNormal: as ActorDescendiente2

ActorDescendiente --|> ActorAscen
ActorDescendiente2 --|>ActorAscen
note right of ActorAscen
Actor Antecesor
end note

note right of ActorDescendiente
Actor descendiente
end note

note right of ActorDescendiente2
Actor descendiente
end note
@enduml
